### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by nicolas-graves** [withoutboats/bpb#11]
Hi! 

Thanks for this package. 

I was trying to package it for guix and noticed dependencies are very old, compared to current versions of the dependencies. 

Do you still use and maintain the package? Would you able able to update it to the more up-to-date versions of dependencies?

**Comment by withoutboats** [comment]
I do not use or maintain this package anymore.

**Comment by nicolas-graves** [comment]
Do you use another alternative to sign commits than GnuPG ? This was originally the reason I tried to use this repo, and it's pretty hard to find information about possible alternatives (and I think yours is the only one I managed to quickly integrate in my git workflow). (This to say I don't understand why you would abandon use in this context). 

Maybe you can put the repo as a public archive or include a warning about it being unupdated since 4 years in the README ?

**Comment by nicolas-graves** [comment]
By the way, I've found this: https://calebhearth.com/sign-git-with-ssh ; that will probably be my choice after bpb. Thanks anyway, best regards !
